spring:
  application:
    name: anoceoc

application:
  anoceoc:
    ANOCEOC_PAGE: anoceocPage
    ANOC_LINK_DESCRIPTION: The Annual Notice of Change compares your current benefits with changes for the coming year to help you make choices for your coverage.
    EOC_LINK_DESCRIPTION: The Evidence of Coverage gives you details about your Medicare Health Benefit and Services and (if applicable) Prescription Drug Coverage for the year.
    FIND_DOCTOR_PHARAMACIES: To search for doctors and/or pharmacies, select Find a Doctor at the top of this page or My Prescription Coverage under My Care.
    NOT_AVAILABLE: Not available
    ANOC_FILE_NAME: Annual Notice of Change
    EOC_FILE_NAME: Evidence of Coverage
    CF_FILE_NAME: Comprehensive Formulary
    FORM_PAGE: formPage
    DIRECT_PHARMACY_REIMBURSEMENT: Direct Pharmacy Reimbursement Form (PDF)
    DIRECT_PHARMACY_LINK: https://www.hap.org/-/media/files/hap/medicare/2019/directpharmacypaymentform.pdf?la=en
    DIRECT_MEDICAL_REIMBURSEMENT: Direct Reimbursement Form – Medical Claim (PDF)
    DIRECT_MEDICAL_LINK: https://www.hap.org/-/media/files/hap/medicare/pdfs/direct-reimbursement-form.pdf?la=en
    HEALTH_REIMBURSEMENT: Reimbursement Form for Health Care Services Provided Outside the U.S. (PDF)
    HEALTH_REIMBURSEMENT_LINK: https://www.hap.org/-/media/files/hap/foreign-claims-reimbursement-form---medicare.pdf?la=en
    REPRESENTATIVE_FORM: Appointment of Representative Form (PDF)
    REPRESENTATIVE_FORM_LINK: https://www.hap.org/-/media/files/hap/medicare/2019/appointing-representative-cms1696.pdf?la=en
    MEDICAL_RIGHTS_FORM: Know Your Medical Rights (Advanced Directive PDF)
    MEDICAL_RIGHTS_FORM_LINK: https://www.hap.org/-/media/files/hap/medicare/pdfs/know-your-medical-rights.pdf?la=en
    AUTHORIZATION_FORM: Authorization for HAP to Release Personal and Health Information (PDF)
    AUTHORIZATION_FORM_LINK: https://www.hap.org/-/media/files/hap/medicare/pdfs/release-form.pdf?la=en
    ADMISSION_FORM: Admission Team Authorization Request
    ADMISSION_FORM_LINK: https://www.hap.org/-/media/files/hap/admission-team-authorization-request-form.pdf?la=en
    REFERRAL_FORM: Outpatient Medical Authorization Request Form
    REFERRAL_FORM_LINK: https://www.hap.org/-/media/files/hap/outpatient-medical-authorization-request-form
    AUTOMACTIC_WITHDRAWAL_FORM: Authorization for Automatic Withdrawal (PDF)
    AUTOMACTIC_WITHDRAWAL_FORM_LINK: https://www.hap.org/-/media/files/hap/medicare/2018/pdfs/automatic-withdrawal-form.pdf?la=en
    PRESCRIPTION_COVERAGE_FORM: Determination Request for Medicare Prescription Drug Coverage (PDF)
    PRESCRIPTION_COVERAGE_FORM_LINK: https://www.hap.org/-/media/files/hap/medicare/2019/determination-request.pdf?la=en
    REPRESENTATIVE_FORM_DES: appoint a doctor, lawyer or family member to request a coverage determination or file an appeal or grievance on your behalf
    MEDICAL_RIGHTS_FORM_DES: understand your right to appoint a representative to act on your behalf
    AUTHORIZATION_FORM_DES: give HAP permission to release personal health information to those you approve
    ADMISSION_FORM_DES: a health care provider is requesting an in-patient admission
    REFERRAL_FORM_DES: request an organization determination (authorization request) for outpatient medical service
    AUTOMACTIC_WITHDRAWAL_FORM_DES: give HAP permission for automatic withdrawals
    PRESCRIPTION_COVERAGE_FORM_DES: ask for prescription drug coverage determination
    formulary2020Medicarepath: https://www.hap.org/-/media/files/hap/2020-mapd-formulary.pdf?la=en   
    
    
    
    