spring:
  application:
    name: bam

bamLink:
  bamLogoLink: <img src="https://www.hap.org/-/media/images/logos/hap/new-newspaper-logo-nowhitespace.svg" class="hap-brand-logo">
  bamHeaderClass: <p class="hap-section-headings">
  bamSubHeaderClass: <p class="heading-text2">
  marginTop: <p class="marginTop">
  liClass: <li class="margin-top-8">