spring:
  application:
    name: cob
    
application:
  cob:
    LABEL_OTHER: Other
    INQUIRY_TYPE_LABEL_NEW: New COB Information
    INQUIRY_TYPE_LABEL_VERIFICATION: Verification of COB determination is needed
    INQUIRY_TYPE_LABEL_UPDATE: Update of COB Information
    INQUIRY_TYPE_LABEL_WORKERS: Possible Workers Compensation Review
    INQUIRY_TYPE_LABEL_AUTO: Possible Auto Accident Review
    INQUIRY_TYPE_LABEL_CANCEL: Cancellation of COB Information
    INQUIRY_TYPE_NEW_CRC: 1141
    INQUIRY_TYPE_VERIFICATION_CRC: 1141
    INQUIRY_TYPE_UPDATE_CRC: 1141
    INQUIRY_TYPE_WORKERS_CRC: 1141
    INQUIRY_TYPE_AUTO_CRC: 1141
    INQUIRY_TYPE_CANCEL_CRC: 1141
    MEMBER_NEW_COB_CRC: 1141
    MEMBER_UPDATED_COB_CRC: 1141
    MEMBER_CANCEL_COB_CRC: 1141
    MEMBER_ADD_COB_CRC: 1141
    HIT_MEMBER_USER: MCOB-INT