spring:
  application:
    name: mhr

mhrMessage:
   errorMessage:
     notViewableAgeMessage: The selected member is currently active. However, due to HIPAA regulations, you may only view information for yourself and dependents under the age of 18.
     notViewableTpaMessage: Authorizations for HAP Preferred PPO enrollees are not available on the HAP Web site. Please contact BENESYS INC, AHL at (248)813-9800.
     notViewableCignaMessage: Authorizations for CIGNA plans are not available through this system. Please contact CIGNA at
     noAuthorizationsfound: You currently have no active contracts.
     tpaMessage: Eligibility and Benefit Information for HAP Preferred PPO members is not available through this system. Please contact
   preventiveDesc:
     descSeat: Car Seat Use
     descNutriAssesment: Nutrition and Exercise Assessment
     descSuddenInfant: Sudden Infant Death Syndrome (SIDS)
     descInjPre: Injury Prevention
     descSunExp: Sun Exposure and Skin Lesions
     descSeatBelt: Seat Belt Use
     descDentalHealth: Dental Health
     descSafePractice: Safe Sexual Practices
     descIncBirth: Including Birth Control
     descDepScreen: Depression Screening
     descTobacco: Tobacco
     descAlcohol: Alcohol
     descDrug: Drug Use
     descAlchAbuse: Alcohol Abuse Screening
     descBodyMass: Body Mass Index Measurement
     descSmoking: Smoking Status Check
   preventiveLinks:
     motorLink: /health/teenadult/motor.php
     indexLink: /health/teenadult/index.php
     sidsLink: http://www.hap.org/health/children/sids.php
     childinjLink: http://www.hap.org/health/children/childinj.php
     skinLink: http://www.hap.org/health/teens/skin.php
     psgLink: /gfx/content/psg/31_1.pdf#zoom=100
     cageLink: /CAGE-TWEAK.pdf#zoom=10
     contraLink: http://www.hap.org/health/women/contra.php
     depressionLink: /depression.pdf#zoom=100
     stdPrevLink: /health/womens/stdprev.php
     quittingLink: /health/smoking/quitting.php
     treatmentLink: /health/cbhm/cbhm_treatment.php
     bmiLink: http://www.cdc.gov/nccdphp/dnpa/bmi/index.htm
     fallsLink: http://www.hap.org/health/seniors/falls.php     
     
      
    