spring:
  application:
    name: sso
    
properties:
  serverUrlLabel: serverUrl
  partnerSpIdLabel: PartnerSpId
  pingSAMLPost : PingSAMLPost
  subject : subject
  postSSO : postSSO
  relayStateLabel : RelayState
  
  utilProperties: 
    pfStartSSOEndPointIDP: /idp/startSSO.ping
    pfStartSSOEndPointSP : /sp/startSSO.ping
    refIdDropOffURL: /ext/ref/dropoff
    refIdPickUpURL: /ext/ref/pickup
    clientKeyFilePassword : password    
  healthEquity:
    partnerId: PartnerId
    partnerIdValue: P_HAP
    insuredId: InsuredID
  fitnessAndSurvey: 
    firstNameKey: FirstName
    lastNameKey: LastName
    subscriberIdKey: UniqueMemberID
    suffixKey : MemberSuffix
    dateOfBirthKey: DateOfBirth
  webmd:
    pageParameter: goTo
    healthAssessmentPage: assessment
    startIdHomePage: 87
    startIdHealthAssessment: 3563
    tlid: 752
    startIdRewardHealth: 384
    rewardHealthPage: rewardYourHealth
    idAttrName: ID
    utcAttrName: UTC
    tlidAttrName: TLID
    startIdAttrName: StartID
    loginssoRedirectCustomLogin: /hapPortal/portalaction/dispatch.do?method=customLogin&ssoPartner=WebMDMobile
    medicaidText: You are leaving a Medicaid-approved site. 
    medicareText: You are leaving a Health Alliance Plan's web site. 
    commercialText: You are leaving a Health Alliance Plan's web site. 
  esi:
    carrierIdHAPCommKey: 8488
    carrierIdHAPCommValue: HAPL
    carrierIdHAPAHLKey: 8489
    carrierIdHAPAHLValue: HAPA
    carrierIdHAPMEDDKey: 8490
    carrierIdHAPMEDDValue: HAPM
    carrierIdHAPMANORXKey: 8493
    carrierIdHAPMANORXValue: HAMR
    carrierIdMWHAMCKey: 8492
    carrierIdMWHAMCValue: HAMC
    carrierIdMWMMPKey: 8491
    carrierIdMWMMPValue: HMMP
    relationshipMember: M
    relationshipHusband: H
    relationshipWife: W
    relationshipDaughter: D
    relationshipSon: S
    relationshipCodeMember: 1
    relationshipCodeDependent: 3
    relationshipCodeDomesticPartner1: 8
    relationshipCodeDomesticPartner2: 2
    dateTime: datetime
    medicaidText: You are leaving Medicaid-approved site.
    medicareText: You are leaving Health Alliance Plan's web site.
    commercialText: You are leaving Health Alliance Plan's web site.
    