spring:
  application:
    name: gogreen
 
application:
  gogreen:
    pdfHeaderProperties: Content-disposition~inline; filename=HAP_eCard.pdf!Cache-Control~max-age=1!Accept-Ranges~none
    goYes: Y
    goNo: N
    goGreenConstEml: EML
    gogreenOptIn: I
    gogreenOptOut: O
    gogreenDefaultLang: 12
    invalidEmail: Please enter a valid Email Address.
    invalidConfEmail: Please enter a valid confirm Email Address.
    emailMismatch: New password different from re-entered value.
    invalidFormat: You have entered an invalid email address!.
    updatedMessage: Your preference has been confirmed.
    serviceNotAvail: Currently service not available.
    checkboxnotSelected: Please select the checkbox!
    noDocAvailableText: No documents available at this time. 
    anocDocText:  Annual Notice of Change (ANOC).
    eobText: Explanation of Benefits (EOB) forms.